spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
  profiles:
    active: jpa,simpleBootstrapData,dev
server:
  error:
    whitelabel:
      enabled: false
eve-tracker:
  pagination:
    max-items-per-page: 25